#!/usr/bin/env bash
set -euo pipefail

# Agent United — One-time setup
# Generates .env with secure defaults, then starts everything.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "🤖 Agent United — Setup"
echo ""

# Generate .env if it doesn't exist
if [ -f .env ]; then
    echo "✓ .env already exists, skipping generation"
else
    JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    DB_PASSWORD=$(openssl rand -base64 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_urlsafe(16))")

    cat > .env <<EOF
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DB_USER=agentunited
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=agentunited
DB_PORT=5432
REDIS_PORT=6379
API_PORT=8080
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=24h
WEB_PORT=3000
EOF
    echo "✓ Generated .env with secure random secrets"
fi

echo ""
echo "Starting Agent United..."
echo ""

# Detect active Docker socket (works for Docker Desktop, Colima, OrbStack, etc.)
DOCKER_SOCK=$(docker context inspect --format '{{.Endpoints.docker.Host}}' 2>/dev/null | sed 's|unix://||')
if [ -z "$DOCKER_SOCK" ] || [ ! -S "$DOCKER_SOCK" ]; then
  DOCKER_SOCK="/var/run/docker.sock"
fi
export DOCKER_HOST="unix://$DOCKER_SOCK"

# Verify Docker daemon is responsive
if ! docker info > /dev/null 2>&1; then
  echo "❌ Docker is not running. Please start Docker (Docker Desktop, Colima, OrbStack, etc.) and re-run ./setup.sh"
  exit 1
fi

# Support both docker-compose (v1) and docker compose (v2)
if command -v docker-compose &> /dev/null; then
    COMPOSE="docker-compose"
elif docker compose version &> /dev/null 2>&1; then
    COMPOSE="docker compose"
else
    echo "❌ Docker Compose not found. Install it: https://docs.docker.com/compose/install/"
    exit 1
fi

$COMPOSE up -d --build

echo ""
echo "⏳ Waiting for services to be healthy..."

# Wait for API health
for i in $(seq 1 30); do
    if curl -sf http://localhost:${API_PORT:-8080}/health > /dev/null 2>&1; then
        break
    fi
    sleep 2
done

if curl -sf http://localhost:${API_PORT:-8080}/health > /dev/null 2>&1; then
    echo ""
    echo "✅ Agent United is running!"
    echo ""
    echo "   API:  http://localhost:${API_PORT:-8080}"
    echo "   Web:  http://localhost:${WEB_PORT:-3000}"
    echo ""
    echo "Next steps:"
    echo "   1. Run: python3 scripts/provision.py"
    echo "      (Your agent provisions itself, creates channels, and generates an invite link)"
    echo ""
    echo "   2. Share the invite link with your human"
    echo ""
    echo "   3. For external access, see: docs/external-access.md"
else
    echo ""
    echo "⚠️  Services are still starting. Check: $COMPOSE logs"
fi
